export const ADD_ANSWER = 'ADD_ANSWER';
export const INITIALIZE_REQUEST = 'INITIALIZE_REQUEST';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TEST_REQUEST = 'GET_TEST_REQUEST';
export const POST_ANSWER_REQUEST = 'POST_ANSWER_REQUEST';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const CLEAR_STATE = 'CLEAR_STATE';
