export const ADD_ANSWER = 'ADD_ANSWER';
export const POST_ANSWER_INITIALIZER = 'POST_ANSWER_INITIALIZER';
export const POST_ANSWER_SUCCESS = 'POST_ANSWER_SUCCESS';
export const POST_ANSWER_FAILURE = 'POST_ANSWER_FAILURE';
